version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: docker/dockerfile.api

    ports:
      - "8000:8000"

    volumes:
      - .:/app

  streamlit:
    build:
      context: .
      dockerfile: docker/dockerfile.streamlit

    ports:
      - "8501:8501"

    volumes:
      - .:/app

    depends_on:
      - api

  uptime-kuma:
    image: louislam/uptime-kuma

    container_name: uptime-kuma

    ports:
      - "3001:3001"

    volumes:
      - kuma_data:/app/data

volumes:
  kuma_data:
